import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import './app.css';
import { addMonthsClamped, annualizedCost } from '../lib/calculations';
import { base, clearDatabase, db, now, snapshot, uid } from '../lib/db';
import type { AppSnapshot, Asset, Contact, DocumentRecord, HouseholdEvent, HouseholdTask, MaintenanceTask, Subscription, Warranty } from '../lib/db/types';
import { createBackup, decryptBackup, encryptBackup, restoreBackup } from '../lib/backup';

type Tab = 'today' | 'assets' | 'maintenance' | 'tasks' | 'warranties' | 'subscriptions' | 'emergency' | 'documents' | 'handoff' | 'display' | 'settings';
type Input = { name: string; label: string; type?: string; required?: boolean; options?: string[]; value?: string; help?: string };
const empty: AppSnapshot = { households: [], members: [], assets: [], maintenanceTasks: [], maintenanceEvents: [], tasks: [], events: [], warranties: [], subscriptions: [], contacts: [], documents: [], handoffProfiles: [], settings: [] };
const labelDate = (value: string) => value ? new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(`${value}T12:00:00`)) : 'No date';
const dueStatus = (value: string) => !value ? 'No date' : value < new Date().toISOString().slice(0, 10) ? 'Overdue' : value === new Date().toISOString().slice(0, 10) ? 'Due today' : `Due ${labelDate(value)}`;
const download = (name: string, value: unknown) => { const href = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = href; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(href), 1000); };

function QuickForm({ title, fields, submitLabel = 'Add record', onSubmit }: { title: string; fields: Input[]; submitLabel?: string; onSubmit: (values: Record<string, string>) => Promise<void> }) {
  const initial = useMemo(() => Object.fromEntries(fields.map((field) => [field.name, field.value || field.options?.[0] || ''])), [fields]);
  const [values, setValues] = useState<Record<string, string>>(initial);
  const [busy, setBusy] = useState(false);
  return <form className="app-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); try { await onSubmit(values); setValues(initial); } finally { setBusy(false); } }}>
    <h2>{title}</h2><div className="form-grid">{fields.map((field) => <label key={field.name}>{field.label}
      {field.options ? <select value={values[field.name]} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })}>{field.options.map((option) => <option key={option} value={option}>{option || 'None'}</option>)}</select>
        : field.type === 'textarea' ? <textarea value={values[field.name]} required={field.required} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })} />
        : <input type={field.type || 'text'} value={values[field.name]} required={field.required} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })} />}
      {field.help && <span className="help">{field.help}</span>}
    </label>)}</div><button disabled={busy} type="submit">{busy ? 'Saving…' : submitLabel}</button>
  </form>;
}

function Empty({ children }: { children: ReactNode }) { return <div className="app-empty">{children}</div>; }

export default function FamilyApp() {
  const [data, setData] = useState<AppSnapshot>(empty);
  const [ready, setReady] = useState(false);
  const [tab, setTab] = useState<Tab>('today');
  const [message, setMessage] = useState('');
  const household = data.households[0];
  const householdId = household?.id || '';
  const refresh = useCallback(async () => { setData(await snapshot()); setReady(true); }, []);
  useEffect(() => { refresh(); navigator.storage?.persist?.().catch(() => false); }, [refresh]);
  const names = useMemo(() => Object.fromEntries(data.members.map((member) => [member.id, member.name])), [data.members]);
  const assets = useMemo(() => Object.fromEntries(data.assets.map((asset) => [asset.id, asset.name])), [data.assets]);

  if (!ready) return <div className="onboarding"><p>Opening your local household database…</p></div>;
  if (!household) return <Onboarding onComplete={refresh} />;

  const title: Record<Tab, [string, string]> = {
    today: ['Today', 'What needs attention across this household.'], assets: ['Assets', 'Appliances, vehicles and household systems worth remembering.'], maintenance: ['Maintenance', 'Recurring work with a completion history.'], tasks: ['Tasks & calendar', 'One-off responsibilities and lightweight household events.'], warranties: ['Warranties', 'Coverage dates, receipt references and review points.'], subscriptions: ['Subscriptions', 'Recurring household obligations and renewal dates.'], emergency: ['Emergency contacts', 'Operational contacts and instructions—kept local.'], documents: ['Document index', 'References to where household records live.'], handoff: ['Household handoff', 'A readable briefing for the next person.'], display: ['Family display', 'A large, low-sensitivity household overview.'], settings: ['Settings & backups', 'Data durability, exports and destructive actions.']
  };

  const save = async (action: () => Promise<unknown>) => { await action(); await refresh(); setMessage('Saved locally on this device.'); setTimeout(() => setMessage(''), 2400); };
  const memberOptions = ['', ...data.members.filter((member) => !member.archived).map((member) => member.id)];
  const assetOptions = ['', ...data.assets.filter((asset) => asset.status !== 'archived').map((asset) => asset.id)];

  return <div className="app-shell">
    <header className="app-topbar"><a className="brand" href="/"><span className="brand-mark">⌂</span>FamilyBoard</a><span className="privacy-pill">Local data · no app analytics</span><span>{household.name}</span></header>
    <div className="app-layout"><nav className="app-nav" aria-label="App sections">{([['today','Today'],['assets','Assets'],['maintenance','Maintenance'],['tasks','Tasks'],['warranties','Warranties'],['subscriptions','Subscriptions'],['emergency','Emergency'],['documents','Documents'],['handoff','Handoff'],['display','Display'],['settings','Settings']] as [Tab,string][]).map(([key, label]) => <button className={tab === key ? 'active' : ''} aria-current={tab === key ? 'page' : undefined} onClick={() => setTab(key)} key={key}>{label}</button>)}</nav>
      <main className="app-main"><div className="app-title"><div><h1>{title[tab][0]}</h1><p>{title[tab][1]}</p></div><button className="secondary no-print" onClick={() => setTab('today')}>Home</button></div>{message && <p className="app-success" role="status">{message}</p>}
        {tab === 'today' && <Today data={data} names={names} assets={assets} setTab={setTab} />}
        {tab === 'assets' && <><QuickForm title="Add an asset" fields={[{name:'name',label:'Asset name',required:true},{name:'category',label:'Category',value:'Appliance'},{name:'location',label:'Location'},{name:'brand',label:'Brand'},{name:'model',label:'Model'},{name:'serialNumber',label:'Serial number',help:'Shared display never shows this value.'},{name:'purchaseDate',label:'Purchase date',type:'date'},{name:'notes',label:'Notes',type:'textarea'}]} onSubmit={(v) => save(() => db.assets.add({ ...base(householdId), ...v, status:'active' } as Asset))} /><div className="app-grid">{data.assets.map((item) => <div className="app-card" key={item.id}><header><h2>{item.name}</h2><span className={`status ${item.status === 'watch' ? 'attention' : ''}`}>{item.status}</span></header><p>{item.category} · {item.location || 'No location'}</p><p className="detail">{[item.brand,item.model].filter(Boolean).join(' ') || 'Brand/model not recorded'} · purchased {labelDate(item.purchaseDate)}</p><div className="app-actions"><button className="secondary" onClick={() => save(() => db.assets.update(item.id,{status:item.status === 'watch'?'active':'watch',updatedAt:now()}))}>{item.status === 'watch'?'Clear watch':'Watch'}</button><button className="secondary" onClick={() => save(() => db.assets.update(item.id,{status:'archived',updatedAt:now()}))}>Archive</button></div></div>)}</div></>}
        {tab === 'maintenance' && <><QuickForm title="Add maintenance" fields={[{name:'title',label:'Maintenance task',required:true},{name:'assetId',label:'Related asset',options:assetOptions},{name:'homeArea',label:'Home area'},{name:'ownerMemberId',label:'Owner',options:memberOptions},{name:'nextDue',label:'Next due',type:'date'},{name:'intervalMonths',label:'Repeat months after completion',type:'number',value:'0'},{name:'priority',label:'Priority',options:['normal','high','low']},{name:'instructionsSource',label:'Instructions source',help:'Manual, official support page or provider.'},{name:'notes',label:'Notes',type:'textarea'}]} onSubmit={(v) => save(() => db.maintenanceTasks.add({ ...base(householdId), ...v, intervalMonths:Number(v.intervalMonths||0), triggerType:Number(v.intervalMonths)>0?'interval-after-completion':'date' } as MaintenanceTask))} /><div className="app-grid">{data.maintenanceTasks.map((item) => <div className="app-card" key={item.id}><header><h2>{item.title}</h2><span className={`status ${item.nextDue && item.nextDue < new Date().toISOString().slice(0,10)?'overdue':''}`}>{dueStatus(item.nextDue)}</span></header><p>{assets[item.assetId] || item.homeArea || 'Whole household'} · {names[item.ownerMemberId] || 'Unassigned'}</p><p className="detail">Source: {item.instructionsSource || 'Add manufacturer/provider source'} · {data.maintenanceEvents.filter((event) => event.maintenanceTaskId === item.id).length} completions</p><div className="app-actions"><button onClick={() => save(async () => { await db.maintenanceEvents.add({ ...base(householdId), maintenanceTaskId:item.id,completedAt:now(),completedBy:'',cost:0,notes:'' }); const nextDue=item.intervalMonths>0?addMonthsClamped(new Date().toISOString().slice(0,10),item.intervalMonths):''; await db.maintenanceTasks.update(item.id,{nextDue,updatedAt:now()}); })}>Complete</button></div></div>)}</div></>}
        {tab === 'tasks' && <TasksView data={data} householdId={householdId} memberOptions={memberOptions} names={names} save={save} />}
        {tab === 'warranties' && <><QuickForm title="Add a warranty" fields={[{name:'assetId',label:'Asset',options:assetOptions,required:true},{name:'provider',label:'Provider'},{name:'startsAt',label:'Starts',type:'date'},{name:'endsAt',label:'Ends',type:'date',required:true},{name:'receiptReference',label:'Receipt location/reference'},{name:'termsReference',label:'Terms/manual reference'},{name:'notes',label:'Notes',type:'textarea'}]} onSubmit={(v) => save(() => db.warranties.add({ ...base(householdId), ...v } as Warranty))} /><div className="app-grid">{data.warranties.map((item) => <div className="app-card" key={item.id}><header><h2>{assets[item.assetId] || 'Unlinked warranty'}</h2><span className={`status ${item.endsAt < new Date().toISOString().slice(0,10)?'overdue':''}`}>{item.endsAt < new Date().toISOString().slice(0,10)?'Expired':`Ends ${labelDate(item.endsAt)}`}</span></header><p>{item.provider || 'Provider not recorded'}</p><p className="detail">Receipt: {item.receiptReference || 'Not recorded'} · Written terms control exact coverage.</p></div>)}</div></>}
        {tab === 'subscriptions' && <><QuickForm title="Add a subscription" fields={[{name:'name',label:'Service',required:true},{name:'category',label:'Category',value:'Household'},{name:'cost',label:'Cost',type:'number',value:'0'},{name:'currency',label:'Currency',value:'USD'},{name:'billingFrequency',label:'Billing frequency',options:['monthly','annual','weekly','quarterly']},{name:'nextRenewal',label:'Next renewal',type:'date'},{name:'reviewBeforeDays',label:'Review days before',type:'number',value:'14'},{name:'ownerMemberId',label:'Owner',options:memberOptions},{name:'managementUrl',label:'Management URL',type:'url'},{name:'paymentMethodNote',label:'Non-sensitive payment note',help:'Never store card numbers or passwords.'},{name:'notes',label:'Notes',type:'textarea'}]} onSubmit={(v) => save(() => db.subscriptions.add({ ...base(householdId), ...v, cost:Number(v.cost||0), reviewBeforeDays:Number(v.reviewBeforeDays||0), status:'active' } as Subscription))} /><p className="notice">Annualized active total: {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(data.subscriptions.filter((item)=>item.status==='active').reduce((sum,item)=>sum+annualizedCost(item.cost,item.billingFrequency),0))}</p><div className="app-grid">{data.subscriptions.map((item) => <div className="app-card" key={item.id}><header><h2>{item.name}</h2><span className="status">{item.status}</span></header><p>{item.currency} {item.cost.toFixed(2)} · {item.billingFrequency}</p><p className="detail">Renewal {labelDate(item.nextRenewal)} · {names[item.ownerMemberId] || 'Unassigned'}</p><div className="app-actions"><button className="secondary" onClick={() => save(() => db.subscriptions.update(item.id,{status:item.status==='cancelled'?'active':'cancelled',updatedAt:now()}))}>{item.status==='cancelled'?'Reactivate':'Mark cancelled'}</button></div></div>)}</div></>}
        {tab === 'emergency' && <><QuickForm title="Add a contact" fields={[{name:'name',label:'Person or service',required:true},{name:'category',label:'Category',value:'Household contact'},{name:'phone',label:'Phone',type:'tel'},{name:'email',label:'Email',type:'email'},{name:'notes',label:'Operational notes',type:'textarea'},{name:'sensitive',label:'Visibility',options:['false','true'],help:'Sensitive contacts are excluded from shared display and handoff by default.'}]} onSubmit={(v) => save(() => db.contacts.add({ ...base(householdId), ...v, sensitive:v.sensitive==='true' } as Contact))} /><div className="app-grid">{data.contacts.map((item) => <div className="app-card" key={item.id}><header><h2>{item.name}</h2><span className={`status ${item.sensitive?'attention':''}`}>{item.sensitive?'Private':'Shareable'}</span></header><p>{item.category}</p><p>{item.phone} {item.email}</p><p className="detail">{item.notes}</p></div>)}</div><p className="notice">FamilyBoard organizes contacts; it does not replace current official local emergency guidance.</p></>}
        {tab === 'documents' && <><QuickForm title="Add a document reference" fields={[{name:'name',label:'Record name',required:true},{name:'category',label:'Category',value:'Home record'},{name:'locationReference',label:'Where the original is stored',required:true},{name:'relatedAssetId',label:'Related asset',options:assetOptions},{name:'reviewDate',label:'Review date',type:'date'},{name:'notes',label:'Notes',type:'textarea'}]} onSubmit={(v) => save(() => db.documents.add({ ...base(householdId), ...v } as DocumentRecord))} /><div className="app-grid">{data.documents.map((item) => <div className="app-card" key={item.id}><h2>{item.name}</h2><p>{item.category} · {item.locationReference}</p><p className="detail">{assets[item.relatedAssetId] || 'No asset link'} · review {labelDate(item.reviewDate)}</p></div>)}</div><p className="notice">This v1 stores document references, not uploaded document files. Keep durable originals in storage you control.</p></>}
        {tab === 'handoff' && <HandoffView data={data} names={names} assets={assets} />}
        {tab === 'display' && <DisplayView data={data} names={names} />}
        {tab === 'settings' && <SettingsView data={data} refresh={refresh} householdName={household.name} setMessage={setMessage} />}
      </main></div>
  </div>;
}

function Onboarding({ onComplete }: { onComplete: () => Promise<void> }) {
  const [name, setName] = useState(''); const [members, setMembers] = useState(''); const [busy, setBusy] = useState(false);
  return <div className="onboarding"><form className="onboarding-panel" onSubmit={async (event) => { event.preventDefault(); setBusy(true); const id=uid(); const timestamp=now(); await db.transaction('rw',db.households,db.members,async()=>{ await db.households.add({id,name:name.trim(),createdAt:timestamp,updatedAt:timestamp,schemaVersion:1}); const rows=members.split(',').map((item)=>item.trim()).filter(Boolean).map((member)=>({...base(id),name:member,role:'Household member'})); if(rows.length) await db.members.bulkAdd(rows); }); await onComplete(); }}><span className="eyebrow">No account needed</span><h1>Set up your home without creating an account.</h1><p>Your core household records stay in this browser. Start with one home and the people who share it. Export a backup after adding anything important.</p><label>Home name<input required value={name} onChange={(event)=>setName(event.target.value)} placeholder="Our home" /></label><label>Household members <span className="help">Optional, separated by commas</span><input value={members} onChange={(event)=>setMembers(event.target.value)} placeholder="Alex, Sam" /></label><p className="notice">Browser data can be cleared and devices can fail. FamilyBoard will remind you to export backups.</p><button disabled={busy}>{busy?'Creating local home…':'Create local household'}</button></form></div>;
}

function Today({ data, names, assets, setTab }: { data: AppSnapshot; names: Record<string,string>; assets: Record<string,string>; setTab:(tab:Tab)=>void }) {
  const active=data.tasks.filter((item)=>!item.completedAt); const overdue=active.filter((item)=>item.dueDate&&item.dueDate<new Date().toISOString().slice(0,10)); const dueMaintenance=data.maintenanceTasks.filter((item)=>item.nextDue&&item.nextDue<=new Date(Date.now()+7*86400000).toISOString().slice(0,10));
  return <><div className="metric-grid"><div className="metric"><strong>{overdue.length}</strong><span>Overdue tasks</span></div><div className="metric"><strong>{dueMaintenance.length}</strong><span>Maintenance due soon</span></div><div className="metric"><strong>{data.assets.filter((item)=>item.status!=='archived').length}</strong><span>Active assets</span></div><div className="metric"><strong>{data.subscriptions.filter((item)=>item.status==='active').length}</strong><span>Active subscriptions</span></div></div><div className="app-grid"><section className="app-card"><header><h2>Next responsibilities</h2><button className="secondary" onClick={()=>setTab('tasks')}>View tasks</button></header>{active.slice(0,5).map((item)=><p key={item.id}><strong>{item.title}</strong><br/><span className="detail">{dueStatus(item.dueDate)} · {names[item.ownerMemberId]||'Unassigned'}</span></p>)}{!active.length&&<Empty>Nothing needs your attention right now. Add a responsibility when you have something worth remembering.</Empty>}</section><section className="app-card"><header><h2>Maintenance due</h2><button className="secondary" onClick={()=>setTab('maintenance')}>View maintenance</button></header>{dueMaintenance.slice(0,5).map((item)=><p key={item.id}><strong>{item.title}</strong><br/><span className="detail">{assets[item.assetId]||item.homeArea||'Household'} · {dueStatus(item.nextDue)}</span></p>)}{!dueMaintenance.length&&<Empty>No maintenance is due in the next seven days.</Empty>}</section></div></>;
}

function TasksView({ data, householdId, memberOptions, names, save }: { data:AppSnapshot; householdId:string; memberOptions:string[]; names:Record<string,string>; save:(action:()=>Promise<unknown>)=>Promise<void> }) {
  return <><QuickForm title="Add a task" fields={[{name:'title',label:'Responsibility',required:true},{name:'ownerMemberId',label:'Owner',options:memberOptions},{name:'dueDate',label:'Due date',type:'date'},{name:'recurrence',label:'Repeat note',help:'Example: weekly. Completing does not invent the next date.'},{name:'notes',label:'Notes',type:'textarea'}]} onSubmit={(v)=>save(()=>db.tasks.add({...base(householdId),...v,completedAt:''} as HouseholdTask))}/><QuickForm title="Add a calendar event" fields={[{name:'title',label:'Event',required:true},{name:'startsAt',label:'Starts',type:'datetime-local',required:true},{name:'endsAt',label:'Ends',type:'datetime-local'},{name:'location',label:'Location'},{name:'notes',label:'Notes',type:'textarea'}]} onSubmit={(v)=>save(()=>db.events.add({...base(householdId),...v} as HouseholdEvent))}/><div className="app-grid">{data.tasks.map((item)=><div className="app-card" key={item.id}><header><h2>{item.title}</h2><span className={`status ${item.completedAt?'':'attention'}`}>{item.completedAt?'Complete':dueStatus(item.dueDate)}</span></header><p>{names[item.ownerMemberId]||'Unassigned'} · {item.recurrence||'One-off'}</p>{!item.completedAt&&<div className="app-actions"><button onClick={()=>save(()=>db.tasks.update(item.id,{completedAt:now(),updatedAt:now()}))}>Complete</button></div>}</div>)}{data.events.map((item)=><div className="app-card" key={item.id}><span className="card-tag">Calendar event</span><h2>{item.title}</h2><p>{new Date(item.startsAt).toLocaleString()} · {item.location||'No location'}</p></div>)}</div></>;
}

function HandoffView({ data, names, assets }: { data:AppSnapshot; names:Record<string,string>; assets:Record<string,string> }) {
  const tasks=data.tasks.filter((item)=>!item.completedAt); const contacts=data.contacts.filter((item)=>!item.sensitive); return <><div className="handoff-sheet"><h2>{data.households[0]?.name} household handoff</h2><p>Generated {new Date().toLocaleString()} · Confirm dates before sharing.</p><h3>Responsibilities</h3>{tasks.length?tasks.map((item)=><p key={item.id}><strong>{item.title}</strong> — {dueStatus(item.dueDate)} — {names[item.ownerMemberId]||'Unassigned'}</p>):<p>Nothing currently open.</p>}<h3>Maintenance</h3>{data.maintenanceTasks.slice(0,10).map((item)=><p key={item.id}><strong>{item.title}</strong> — {assets[item.assetId]||item.homeArea||'Household'} — {dueStatus(item.nextDue)}</p>)}<h3>Shareable contacts</h3>{contacts.map((item)=><p key={item.id}><strong>{item.name}</strong> — {item.category} — {item.phone}</p>)}<h3>Intentionally excluded</h3><p>Sensitive contacts, serial numbers, document details, subscription costs, private notes and backup contents.</p></div><div className="app-actions no-print"><button onClick={()=>window.print()}>Print handoff</button></div></>;
}

function DisplayView({ data, names }: { data:AppSnapshot; names:Record<string,string> }) { const today=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}); return <div className="display-mode"><p>{data.households[0]?.name}</p><h1>{today}</h1><div className="app-grid"><section className="app-card"><h2>Household tasks</h2>{data.tasks.filter((item)=>!item.completedAt).slice(0,6).map((item)=><p key={item.id}><strong>{item.title}</strong> · {names[item.ownerMemberId]||'Anyone'} · {dueStatus(item.dueDate)}</p>)}</section><section className="app-card"><h2>Coming up</h2>{data.maintenanceTasks.slice().sort((a,b)=>a.nextDue.localeCompare(b.nextDue)).slice(0,6).map((item)=><p key={item.id}><strong>{item.title}</strong> · {dueStatus(item.nextDue)}</p>)}</section></div><p>Private records and sensitive contacts are hidden from this display.</p></div>; }

function SettingsView({ data, refresh, householdName, setMessage }: { data:AppSnapshot; refresh:()=>Promise<void>; householdName:string; setMessage:(value:string)=>void }) {
  const [password,setPassword]=useState(''); const [restorePassword,setRestorePassword]=useState(''); const [mode,setMode]=useState<'merge'|'replace'>('merge'); const [confirm,setConfirm]=useState(''); const [error,setError]=useState(''); const lastBackup=data.settings.find((item)=>item.id==='lastBackup')?.value;
  const exportData=async(encrypted:boolean)=>{try{setError('');const backup=await createBackup();const output=encrypted?await encryptBackup(backup,password):backup;download(`familyboard-backup-${new Date().toISOString().slice(0,10)}${encrypted?'.encrypted':''}.json`,output);await db.settings.put({id:'lastBackup',value:now(),updatedAt:now()});await refresh();setMessage('Backup exported. Store it somewhere durable and protected.');}catch(caught){setError(caught instanceof Error?caught.message:'Backup failed.');}};
  const restore=async(event:FormEvent<HTMLInputElement>)=>{const file=event.currentTarget.files?.[0];if(!file)return;try{setError('');const raw=JSON.parse(await file.text());const parsed=raw.format==='familyboard-encrypted-backup'?await decryptBackup(raw,restorePassword):raw;if(mode==='replace'){const safety=await createBackup();download(`familyboard-safety-snapshot-${Date.now()}.json`,safety);}await restoreBackup(parsed,mode);await db.settings.put({id:'lastRestore',value:now(),updatedAt:now()});await refresh();setMessage(`Backup restored in ${mode} mode.`);}catch(caught){setError(caught instanceof Error?caught.message:'Restore failed. No changes were applied.');}};
  return <div className="app-grid"><section className="app-card"><h2>Storage health</h2><p>App version: 1.0.0</p><p>Database schema: 1</p><p>Records: {Object.values(data).reduce((sum,items)=>sum+items.length,0)}</p><p>Last backup: {lastBackup?new Date(lastBackup).toLocaleString():'No successful export recorded'}</p><p>Last restore: {data.settings.find((item)=>item.id==='lastRestore')?.value?new Date(data.settings.find((item)=>item.id==='lastRestore')!.value).toLocaleString():'None'}</p></section><section className="app-card"><h2>Export backup</h2><p>Plain JSON is portable but readable. Encrypted export uses PBKDF2-SHA-256 and AES-256-GCM in your browser.</p><label>Encryption password<input type="password" value={password} onChange={(event)=>setPassword(event.target.value)} /></label><div className="app-actions"><button onClick={()=>exportData(false)}>Export JSON</button><button className="secondary" onClick={()=>exportData(true)}>Export encrypted</button></div><p className="help">A forgotten encrypted-backup password cannot be recovered.</p></section><section className="app-card"><h2>Restore backup</h2><label>Mode<select value={mode} onChange={(event)=>setMode(event.target.value as 'merge'|'replace')}><option value="merge">Merge by record ID</option><option value="replace">Replace after safety snapshot</option></select></label><label>Password for encrypted file<input type="password" value={restorePassword} onChange={(event)=>setRestorePassword(event.target.value)} /></label><label>Choose backup<input type="file" accept="application/json,.json" onChange={restore} /></label></section><section className="app-card danger-zone"><h2>Reset local household</h2><p>This removes all FamilyBoard data in this browser. Export a backup first.</p><label>Type “{householdName}” to confirm<input value={confirm} onChange={(event)=>setConfirm(event.target.value)} /></label><div className="app-actions"><button disabled={confirm!==householdName} onClick={async()=>{await clearDatabase();location.reload();}}>Delete local data</button></div></section>{error&&<p className="app-error" role="alert">{error}</p>}</div>;
}
